---
# Location where configuration files will be stored.
config_dir: '~'

# Home Assistant configuation
home_assistant_enable: true

# Home Assistant Supervisor configuation
# This HA configuration is considered advanced and should only be used if one is an expert in managing a Linux operating system, Docker and networking.
home_assistant_supervisor_enable: false
home_assistant_supervisor_version: "1.1.0"
home_assistant_os_agent_version: "1.2.2"

# Enable AirConnect
airconnect_enable: true
